[package]
name = "robonav"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.1"
egui = "0.32.1"
rfd = "0.15.4"
serde = { version = "1.0.227", features = ["derive"] }
serde_json = "1.0.145"
wasm-bindgen-futures = "0.4.50"
